spring: 
#  profiles:
#    active: dev
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root 
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    add-mappings: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level: {root: INFO, com.wotopten.crm.dao: DEBUG}
#interceptor:
#  path:
server:
  port: 8080
#    action: